/* badge_secsea © 2025 by Hack In Provence is licensed under
 * Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * To view a copy of this license,
 * visit https://creativecommons.org/licenses/by-nc-sa/4.0/ */

/** \file gamebook_builtin.h
 *
 * \brief The books of the gamebooks built in the firmware (read from the flash, without SD card), in the same text
 * format as the files of the SD card. gamebook_builtin.c is generated by tools/gamebook_check.py --c.
 * */

#ifndef _GAMEBOOK_BUILTIN_H
#define _GAMEBOOK_BUILTIN_H

#include <stdint.h>

typedef struct {
    const char *key;  /* Identifies the book in the saved progress (like the path of a file) */
    const char *text;
    uint32_t len;
} gamebook_builtin_t;

extern const gamebook_builtin_t gamebook_builtins[];
extern const int gamebook_builtin_count;

#endif /* _GAMEBOOK_BUILTIN_H */
