/* badge_secsea © 2025 by Hack In Provence is licensed under
 * Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
 * To view a copy of this license,
 * visit https://creativecommons.org/licenses/by-nc-sa/4.0/ */

/* The book built in the firmware (no SD card needed), generated from docs/sd/LIVRES/tresor_cigalon.txt by
 *   python tools/gamebook_check.py docs/sd/LIVRES/tresor_cigalon.txt --c src/menu/gamebook_builtin.c
 * Edit the .txt file, then generate this file again. */

#include "gamebook_builtin.h"

static const char BOOK_0[] =
    "Le Trésor du capitaine Cigalon\n"
    "Les cigales de Hack In Provence\n"
    "\n"
    "// Le livre intégré au badge SecSea : un livre dont vous êtes le héros, à La Ciotat.\n"
    "// Format : voir docs/fr/livres_jeux.md. Vérification : python tools/gamebook_check.py ce_fichier.txt\n"
    "// Objets : antenne (l'oratrice), carte et navettes (les goodies), indice (la trame radio).\n"
    "\n"
    "== 1\n"
    "Le soleil de La Ciotat tape déjà sur les grues du port quand vous ouvrez un œil. Vous êtes Cigalou, cigale de son état, hackeuse par vocation, venue à SecSea pour les talks... et pour les navettes.\n"
    "\n"
    "Votre badge vibre. Un message défile :\n"
    "\n"
    "« Le trésor du capitaine Cigalon dort dans les calanques. Premier indice : écoutez. »\n"
    "\n"
    "Sur la terrasse d'en face, la Fourmi, votre éternelle rivale, referme son carnet à spirale et file d'un pas décidé.\n"
    "\n"
    "-> 2 : Foncer à la conférence\n"
    "-> 3 : Chanter un peu d'abord, il fait si beau\n"
    "-> 4 : « Écoutez » ? Allumer la radio du badge\n"
    "\n"
    "== 2\n"
    "La grande salle sent le café et la crème solaire. Sur scène, une oratrice en chemise à fleurs présente « 433 MHz : les sirènes de la Méditerranée ».\n"
    "\n"
    "Sa dernière diapo affiche une phrase étrange : « Là où l'oiseau de pierre ouvre le bec, la mer garde le coffre. »\n"
    "\n"
    "La salle applaudit. L'oratrice range ses câbles ; une antenne télescopique dépasse de son sac.\n"
    "\n"
    "-> 6 : Aller lui parler\n"
    "-> 7 : Filer au stand des goodies\n"
    "-> 8 : Rester assise, le talk suivant parle de café\n"
    "\n"
    "== 3\n"
    "Vous grimpez sur un pin parasol et vous chantez. Vous chantez la mer, le mistral et le sirop d'orgeat. Des touristes filment, un enfant applaudit.\n"
    "\n"
    "La Fourmi passe sous l'arbre, son sac sur le dos.\n"
    "\n"
    "— Vous chantiez ? J'en suis fort aise. Eh bien, cherchez maintenant ! Moi, j'ai déjà un indice.\n"
    "\n"
    "-> 9 : Chanter encore, rien ne presse\n"
    "-> 2 : Descendre et courir à la conférence\n"
    "\n"
    "== 4\n"
    "Vous lancez le récepteur 433 MHz du badge. Une télécommande de portail, une station météo qui annonce 31 degrés... et une trame qui revient toutes les dix secondes, régulière comme un métronome.\n"
    "\n"
    "Les LEDs du badge clignotent en rythme : court, long, court, court...\n"
    "\n"
    "-> 10 : Décoder la trame, ça ressemble à du morse\n"
    "-> 11 : La rejouer telle quelle avec un Flipper\n"
    "\n"
    "== 5 FIN gagné\n"
    "Vous refermez le coffre et le serrez contre vous. La Fourmi hausse les épaules et s'en va sans un mot.\n"
    "\n"
    "Le soir, vous validez le flag : première place du CTF ! On vous applaudit, on vous prend en photo.\n"
    "\n"
    "Mais à la fin de la soirée, la terrasse est vide, et les navettes centenaires sont bien trop dures pour une seule cigale.\n"
    "\n"
    "Vous avez gagné. Un peu seule, mais gagné. Une autre fin vous attend peut-être...\n"
    "\n"
    "== 6\n"
    "L'oratrice sourit en voyant votre badge.\n"
    "\n"
    "— Une cigale ! Le capitaine Cigalon était des vôtres. Il a protégé son coffre par une serrure radio : sans une bonne antenne, aucune chance.\n"
    "\n"
    "Elle vous tend son antenne télescopique.\n"
    "\n"
    "— Rendez-la-moi ce soir. Et méfiez-vous des gabians : ils volent tout ce qui brille.\n"
    "\n"
    "+[antenne]\n"
    "\n"
    "-> 12 : La remercier et partir vers le port\n"
    "-> 7 : Passer d'abord au stand des goodies\n"
    "\n"
    "== 7\n"
    "Le stand des goodies déborde de stickers. Un bénévole vous tend un sac en tissu.\n"
    "\n"
    "— Il reste une carte des calanques et la dernière boîte de navettes. Une seule chose par cigale !\n"
    "\n"
    "-> 13 : Prendre la carte des calanques\n"
    "-> 14 : Prendre les navettes, l'aventure creuse\n"
    "\n"
    "== 8\n"
    "Le talk sur le café est passionnant. Le suivant, sur le café décaféiné, beaucoup moins. Vous vous endormez.\n"
    "\n"
    "Vous rêvez d'un coffre qui chante. Quand vous rouvrez les yeux, la salle est vide et le soleil est déjà bas.\n"
    "\n"
    "-> 15 : Courir au port malgré tout\n"
    "-> 16 : Tant pis pour le trésor, direction l'apéro\n"
    "\n"
    "== 9 FIN perdu\n"
    "Vous chantez tout l'après-midi. Si bien qu'un producteur vous propose un contrat... pour une publicité de climatiseurs.\n"
    "\n"
    "Le soir, la Fourmi revient, un coffre sous le bras.\n"
    "\n"
    "— Vous chantiez ? Eh bien, dansez maintenant !\n"
    "\n"
    "La bise n'est pas venue, mais le trésor est parti. Morale : même en Provence, il faut parfois descendre de son arbre.\n"
    "\n"
    "== 10\n"
    "Court, long, court, court... Vous notez les points et les traits sur le dos de votre patte : B-E-C-A-I-G-L-E.\n"
    "\n"
    "« Bec Aigle » ! Le Bec de l'Aigle, ce cap de roche rouge qui ferme la baie. Ce mot-là pourrait bien resservir.\n"
    "\n"
    "Dans un coin, la Fourmi vous a vue noter. Elle fronce les antennes.\n"
    "\n"
    "+[indice]\n"
    "\n"
    "-> 12 : Courir au port avant elle\n"
    "-> 7 : S'équiper d'abord au stand des goodies\n"
    "\n"
    "== 11\n"
    "Vous rejouez la trame. Rien... puis, dehors, toutes les portes de garage de la rue s'ouvrent en même temps. Un monsieur en marcel sort en criant que c'est la troisième fois cette semaine.\n"
    "\n"
    "Un gendarme à vélo s'arrête. Il regarde votre badge, puis le Flipper, puis vous.\n"
    "\n"
    "-> 17 : Lui expliquer calmement le rejeu radio\n"
    "-> 18 : Partir en courant\n"
    "\n"
    "== 12\n"
    "Le vieux port de La Ciotat brille sous les grues du chantier naval. Au bout de la baie se dresse le Bec de l'Aigle, avec sa tête d'oiseau en roche rouge.\n"
    "\n"
    "Marius, un pêcheur, prépare son pointu, un petit bateau en bois peint en bleu. Derrière lui, un sentier grimpe dans la garrigue, en plein soleil.\n"
    "\n"
    "-> 19 : Demander à Marius de vous emmener\n"
    "-> 20 : Prendre le sentier à pied\n"
    "\n"
    "== 13\n"
    "Vous dépliez la carte. Quelqu'un a entouré au crayon le Bec de l'Aigle et dessiné une croix près de l'eau, avec une note : « Grotte. Par mistral, l'entrée se découvre. »\n"
    "\n"
    "+[carte]\n"
    "\n"
    "-> 12 : Direction le port\n"
    "\n"
    "== 14\n"
    "La boîte sent la fleur d'oranger. Vous croquez une navette : dure comme la roche, délicieuse. Vous gardez les autres, on ne sait jamais.\n"
    "\n"
    "+[navettes]\n"
    "\n"
    "-> 12 : Direction le port\n"
    "\n"
    "== 15\n"
    "Le port est calme. Marius amarre son pointu.\n"
    "\n"
    "— Le trésor ? La Fourmi est partie avec le dernier bateau, il y a une heure. Elle avait l'air pressée.\n"
    "\n"
    "Il hausse les épaules.\n"
    "\n"
    "— Je peux encore vous emmener, mais la mer se lève.\n"
    "\n"
    "-> 19 : Embarquer quand même\n"
    "-> 16 : Laisser tomber et aller à l'apéro\n"
    "\n"
    "== 16 FIN\n"
    "Sur la terrasse, les cigales de SecSea refont le monde : chiffrement, radio, et pourquoi la navette est le meilleur biscuit de l'univers. Quelqu'un parle d'un trésor trouvé par une fourmi.\n"
    "\n"
    "Vous haussez les épaules et commandez un sirop de citron. Pas de trésor aujourd'hui, mais un coucher de soleil sur la baie, ça se partage aussi.\n"
    "\n"
    "L'aventure attendra l'an prochain.\n"
    "\n"
    "== 17\n"
    "Vous expliquez la modulation OOK, les codes fixes des vieux portails, le rejeu. Le gendarme écoute, prend des notes, puis se gratte la tête.\n"
    "\n"
    "— Mon portail aussi est en code fixe ?\n"
    "\n"
    "Vous vérifiez : oui. Il vous remercie chaleureusement et vous montre la direction du port.\n"
    "\n"
    "— Et votre trésor, c'est par là. Tout le monde en parle.\n"
    "\n"
    "-> 12 : Aller au port\n"
    "\n"
    "== 18 FIN perdu\n"
    "Vous courez. Le gendarme aussi, mais il a un vélo.\n"
    "\n"
    "Vous passez l'après-midi au poste à expliquer ce qu'est un Flipper Zero, puis ce qu'est un dauphin, puis pourquoi il y a un dauphin sur le Flipper.\n"
    "\n"
    "Quand on vous relâche, le trésor a été trouvé. Morale : on ne rejoue pas une trame qu'on ne comprend pas.\n"
    "\n"
    "== 19\n"
    "Marius vous fait monter dans le pointu.\n"
    "\n"
    "— Accrochez-vous, le mistral se lève !\n"
    "\n"
    "Le bateau tape dans les vagues, l'eau gicle, le moteur tousse. Marius jure en provençal, ce qui semble aider le moteur.\n"
    "\n"
    "Tout dépend de la mer, maintenant. Le badge lance le dé...\n"
    "\n"
    "-> 21 [dé 1-2] : Une vague énorme arrive...\n"
    "-> 22 [dé 3-6] : La mer se calme un peu\n"
    "\n"
    "== 20\n"
    "Le sentier grimpe entre les pins et les cades. Les pierres sont brûlantes. Vos cousines cigales chantent dans chaque arbre, ce qui n'aide pas à réfléchir.\n"
    "\n"
    "À un croisement, un chemin monte vers le sommet, un autre descend vers la mer.\n"
    "\n"
    "-> 24 [carte] : Suivre la croix de la carte\n"
    "-> 25 : Monter, on verra mieux de là-haut\n"
    "-> 26 : Descendre vers la mer\n"
    "\n"
    "== 21\n"
    "Une vague plus haute que les autres soulève le pointu. Vous passez par-dessus bord... et Marius vous repêche par les ailes avec son épuisette.\n"
    "\n"
    "— Trempée, mais vivante !\n"
    "\n"
    "Le bateau rentre au port pour écoper.\n"
    "\n"
    "-> 20 : Repartir à pied par le sentier\n"
    "-> 16 : Aller sécher sur la terrasse, à l'apéro\n"
    "\n"
    "== 22\n"
    "Le pointu file le long des falaises rouges. Au pied du Bec de l'Aigle, une grotte s'ouvre au ras de l'eau : le mistral a poussé la mer au large et l'entrée est dégagée.\n"
    "\n"
    "Marius coupe le moteur.\n"
    "\n"
    "— Je vous attends. Quand le vent tombera, l'eau remontera : ne traînez pas.\n"
    "\n"
    "-> 23 : Entrer dans la grotte\n"
    "\n"
    "== 23\n"
    "La grotte est fraîche et sent le sel. Au fond, sur un rocher plat, un coffre en bois cerclé de cuivre. Pas de serrure, mais un boîtier noir avec une LED rouge et une étiquette : « 433,92 MHz ».\n"
    "\n"
    "Des pas résonnent derrière vous. C'est la Fourmi, essoufflée, son carnet à la main.\n"
    "\n"
    "— Ce coffre est à moi ! J'ai tout planifié depuis janvier !\n"
    "\n"
    "-> 31 [antenne] : Brancher l'antenne et écouter le boîtier\n"
    "-> 32 : Ouvrir le coffre de force\n"
    "-> 33 : Proposer à la Fourmi de faire équipe\n"
    "\n"
    "== 24\n"
    "Grâce à la carte, vous trouvez un petit chemin caché derrière un buisson de romarin. Il descend en lacets jusqu'à une crique minuscule, au pied du Bec de l'Aigle.\n"
    "\n"
    "Dans la roche s'ouvre une grotte, juste au-dessus de l'eau.\n"
    "\n"
    "-> 23 : Entrer dans la grotte\n"
    "\n"
    "== 25\n"
    "Au sommet, la vue est splendide : la baie, l'Île Verte, les grues du port. Un gabian, l'énorme goéland de Provence, se pose à côté de vous et vous fixe d'un œil jaune.\n"
    "\n"
    "Il regarde votre badge. Il regarde encore votre badge. Il aime ce qui brille.\n"
    "\n"
    "-> 27 [navettes] : Lui offrir une navette\n"
    "-> 28 : Le chasser en battant des ailes\n"
    "-> 20 : Redescendre doucement au croisement\n"
    "\n"
    "== 26\n"
    "Le chemin descend, descend... puis s'arrête net au bord d'une falaise. En bas, la mer turquoise.\n"
    "\n"
    "Vous avez chaud, très chaud. Votre badge affiche une batterie qui transpire.\n"
    "\n"
    "-> 29 : Sauter : vous êtes une cigale, vous avez des ailes !\n"
    "-> 30 : Faire une petite sieste à l'ombre d'un pin\n"
    "-> 20 : Remonter au croisement\n"
    "\n"
    "== 27\n"
    "Le gabian attrape la navette, la croque, réfléchit longuement. Puis il pousse un cri et s'envole vers la falaise, en se retournant comme pour dire : « Suivez-moi. »\n"
    "\n"
    "Il se pose devant une fente dans la roche, juste sous le Bec de l'Aigle. Une grotte !\n"
    "\n"
    "-> 23 : Entrer dans la grotte\n"
    "\n"
    "== 28 FIN perdu\n"
    "Vous battez des ailes. Le gabian aussi, mais il est cinquante fois plus gros que vous. Il attrape votre badge et s'envole vers l'Île Verte, l'écran encore allumé sur la page du trésor.\n"
    "\n"
    "Le soir, on raconte qu'un gabian a appris à envoyer des messages radio.\n"
    "\n"
    "Morale : face à plus gros que soi, une navette vaut mieux qu'un coup d'aile.\n"
    "\n"
    "== 29\n"
    "Vous sautez. Vos ailes vibrent, crépitent... et vous planez ! Bon, surtout vers le bas.\n"
    "\n"
    "Plouf. Vous refaites surface à deux mètres d'une grotte qui s'ouvre au pied du Bec de l'Aigle. Trempée, mais arrivée.\n"
    "\n"
    "-> 23 : Entrer dans la grotte à la nage\n"
    "\n"
    "== 30 FIN perdu\n"
    "Vous vous allongez à l'ombre d'un pin. Juste cinq minutes. Le chant de vos cousines vous berce...\n"
    "\n"
    "Vous vous réveillez à la nuit tombée, avec un coup de soleil sur les antennes. Au loin, sur le port, on fête la Fourmi qui a trouvé le trésor.\n"
    "\n"
    "Morale : la sieste est un art provençal, mais pas pendant une chasse au trésor.\n"
    "\n"
    "== 31\n"
    "Avec l'antenne, le badge capte le boîtier à merveille. Il émet une courte trame toutes les secondes, comme s'il attendait une réponse. Du morse !\n"
    "\n"
    "La Fourmi se penche par-dessus votre épaule.\n"
    "\n"
    "— C'est... malin, admet-elle du bout des mandibules.\n"
    "\n"
    "-> 34 [indice] : Répondre le mot du matin : BECAIGLE\n"
    "-> 36 [!indice] : Tenter le nom du capitaine : CIGALON\n"
    "-> 35 : Envoyer 0000, comme tous les codes par défaut\n"
    "\n"
    "== 32\n"
    "Vous tirez, poussez, tapez. La LED du boîtier passe au rouge vif et une sirène hurle dans toute la grotte.\n"
    "\n"
    "— Bravo, soupire la Fourmi.\n"
    "\n"
    "Dehors, le vent est en train de tomber. L'eau commence à remonter.\n"
    "\n"
    "-> 33 : Proposer à la Fourmi de faire équipe, vite\n"
    "-> 38 : Insister encore, ça va céder\n"
    "\n"
    "== 33\n"
    "La Fourmi hésite. Elle regarde son carnet, puis votre badge, puis encore son carnet.\n"
    "\n"
    "— Bon. Moi j'ai la méthode, vous avez... l'enthousiasme. Moitié-moitié ?\n"
    "\n"
    "Elle tourne une page.\n"
    "\n"
    "— J'ai noté que le capitaine cachait toujours ses mots de passe près de ses coffres.\n"
    "\n"
    "-> 31 [antenne] : Sortir l'antenne et écouter le boîtier ensemble\n"
    "-> 39 : Fouiller la grotte avec elle\n"
    "\n"
    "== 34\n"
    "Vous tapez B-E-C-A-I-G-L-E et le badge l'envoie en morse radio. La LED du boîtier hésite... puis passe au vert.\n"
    "\n"
    "Clac ! Le couvercle du coffre se soulève.\n"
    "\n"
    "-> 37 : Ouvrir le coffre\n"
    "\n"
    "== 35 FIN perdu\n"
    "Vous envoyez 0000. Le boîtier répond aussitôt, en morse : « VRAIMENT ? » Puis la LED devient rouge et le boîtier s'éteint pour vingt-quatre heures. Anti-force brute : le capitaine savait y faire.\n"
    "\n"
    "La Fourmi écrit dans son carnet : « Ne jamais faire équipe avec une cigale. »\n"
    "\n"
    "Morale : les codes par défaut, c'est pour les portails des voisins, pas pour les capitaines.\n"
    "\n"
    "== 36\n"
    "Vous tapez C-I-G-A-L-O-N. Un temps. Puis la LED passe au vert. Clac !\n"
    "\n"
    "— Son propre nom comme mot de passe, soupire la Fourmi. Le capitaine n'aurait pas tenu cinq minutes à un CTF.\n"
    "\n"
    "-> 37 : Ouvrir le coffre\n"
    "\n"
    "== 37\n"
    "Dans le coffre, pas d'or, mais mieux : un vieux poste radio en laiton, des carnets de schémas, une boîte de navettes centenaires dures comme du granit et, gravé sous le couvercle, un flag : SECSEA{P4RT4G3}.\n"
    "\n"
    "La Fourmi vous regarde. Vous regardez la Fourmi.\n"
    "\n"
    "-> 42 : Partager le trésor avec elle\n"
    "-> 5 : Tout garder, c'est vous qui l'avez ouvert\n"
    "\n"
    "== 38 FIN perdu\n"
    "Ça ne cède pas. La mer, elle, monte. Vous sortez de la grotte à la nage en tirant la Fourmi par une patte, juste avant que l'entrée ne disparaisse sous l'eau.\n"
    "\n"
    "Le coffre attendra le prochain coup de mistral.\n"
    "\n"
    "Morale : un coffre se pirate avec la tête, pas avec les pattes.\n"
    "\n"
    "== 39\n"
    "Derrière un rocher, vous trouvez une bouteille. Dedans, un papier roulé : « Pour ouvrir mon coffre, chante-lui mon nom. Capitaine Cigalon. »\n"
    "\n"
    "— Chanter ? La Fourmi lève les yeux au ciel.\n"
    "\n"
    "Vous, vous souriez : chanter, c'est votre spécialité.\n"
    "\n"
    "-> 40 : Chanter « Cigalon » devant le boîtier\n"
    "-> 41 : Laisser la Fourmi essayer d'abord\n"
    "\n"
    "== 40\n"
    "Vous chantez. Fort, juste, avec un trémolo qui ferait pleurer un gabian. La LED passe au vert. Clac ! Le couvercle se soulève.\n"
    "\n"
    "— Un capteur de son, note la Fourmi. Le capitaine était un artiste.\n"
    "\n"
    "-> 37 : Ouvrir le coffre\n"
    "\n"
    "== 41\n"
    "La Fourmi se racle la gorge et récite « Ci-ga-lon » d'une voix de répondeur téléphonique. La LED clignote en rouge. Un bip sec : dernier essai.\n"
    "\n"
    "— Bon, dit-elle. À vous. Il paraît que vous savez faire.\n"
    "\n"
    "-> 40 : Chanter de tout votre cœur\n"
    "\n"
    "== 42 FIN gagné\n"
    "Vous partagez tout. La Fourmi prend les carnets, vous gardez la radio, et vous invitez Marius et l'oratrice à fêter ça.\n"
    "\n"
    "Le soir, sur la terrasse de SecSea, vous racontez l'aventure à toute la conférence : elle prend des notes, vous chantez les rebondissements.\n"
    "\n"
    "L'année suivante, vous ouvrez ensemble un hackerspace sur le port, « La Cigalière ». On y code l'hiver, on y chante l'été.\n"
    "\n"
    "Morale : la cigale et la fourmi, ensemble, c'est encore mieux. Bravo !\n";

const gamebook_builtin_t gamebook_builtins[] = {
    {"builtin/tresor_cigalon.txt", BOOK_0, sizeof(BOOK_0) - 1},
};
const int gamebook_builtin_count = sizeof(gamebook_builtins) / sizeof(gamebook_builtins[0]);
