/* Generated by tools/i18n.py gen from src/menu/lang/*.po: do not edit (docs/fr/traduction.md). */

#include <stddef.h>

#include "i18n.h"

const int I18N_N_LANGS = 2;
const i18n_lang_t I18N_LANGS[] = {
    {"fr", "Français"},
    {"en", "en"},
};

const int I18N_N_TEXTS = 6;

/* The French texts, by FNV-1a hash */
const i18n_text_t I18N_TEXTS[] = {
    {0x1193FDFFu, "Langue"},
    {0x11B416F5u, "Langue : English"},
    {0x1A5898F7u, "Langue : %s"},
    {0xB1CA2CA4u, "G : retour  D : choisir"},
    {0xCC267942u, "Réglages"},
    {0xE1165437u, "Sonnerie %d / %d"},
};

/* en (en): NULL = not translated, the French text is shown */
static const char *const TEXTS_EN[] = {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

/* The translations of each language after the French one */
const char *const *const I18N_TRANSLATIONS[] = {
    TEXTS_EN,
};
