# Writes version.h at each build (cmake -P): the version of the firmware, the git commit and the date of the build.
# Arguments: SRC (the repository), OUT (version.h to write), VERSION (the version number, set in CMakeLists.txt).
# The file is only rewritten when its content changes (otherwise everything that includes it would be compiled again).

execute_process(COMMAND git rev-parse --short HEAD WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE hash OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE git_failed)
if(git_failed OR NOT hash)
    set(hash "sans-git")
endif()
# "+": the sources differ from the commit (only src/ and tools/: the files of the IDE don't count)
execute_process(COMMAND git status --porcelain --untracked-files=no -- src tools WORKING_DIRECTORY ${SRC}
                OUTPUT_VARIABLE dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(dirty)
    set(hash "${hash}+")
endif()
string(TIMESTAMP date "%Y-%m-%d")

set(content "/* Generated by src/menu/version.cmake at each build, do not edit */\n"
            "#define BADGE_VERSION \"${VERSION}\"\n"
            "#define BADGE_BUILD \"${hash} ${date}\"\n")
string(CONCAT content ${content})
if(EXISTS ${OUT})
    file(READ ${OUT} old)
endif()
if(NOT "${old}" STREQUAL "${content}")
    file(WRITE ${OUT} "${content}")
endif()
