#!/usr/bin/env python3

# badge_secsea © 2025 by Hack In Provence is licensed under
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International.
# To view a copy of this license,
# visit https://creativecommons.org/licenses/by-nc-sa/4.0/

"""
The portraits of the 10 pirate ranks (the level of the achievements, src/menu/achievements.c; Badge > Mon grade):
64 x 64 pixels each (shown twice as big on the badge), black and white, drawn here with Pillow. Our own drawings.
Edit them here, then regenerate the C arrays in src/menu/rank.c (between the markers "BEGIN PORTRAITS" and
"END PORTRAITS"):

    python tools/pirate_ranks.py              # rewrites the portraits in src/menu/rank.c
    python tools/pirate_ranks.py --png a.png  # contact sheet of the portraits (zoom 3), to check them
    python tools/pirate_ranks.py --check      # exit code 1 when rank.c is not up to date

The C arrays: 8 bytes per row (64 rows), bit 7 of each byte is the leftmost pixel, 1 = black.
"""

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

SIZE = 64
HERE = os.path.dirname(os.path.abspath(__file__))
C_FILE = os.path.normpath(os.path.join(HERE, '..', 'src', 'menu', 'rank.c'))
BEGIN = '/* BEGIN PORTRAITS (generated by tools/pirate_ranks.py: edit the drawings there) */'
END = '/* END PORTRAITS */'

# Same order as LEVEL_NAMES in src/menu/achievements.c
RANKS = ['Moussaillon', "Pirate d'eau douce", 'Matelot', 'Canonnier', 'Flibustier', 'Boucanier', 'Corsaire',
         'Capitaine Fracasse', 'Barbe-Bleue', 'Barbe-Noire']

B, W = 1, 0  # Ink, paper (mode '1': 1 = white in Pillow, inverted when exported)


class Pic:
    def __init__(self):
        self.img = Image.new('1', (SIZE, SIZE), 1)
        self.d = ImageDraw.Draw(self.img)

    def ink(self, c):
        return 0 if c == B else 1

    def ellipse(self, box, fill=None, outline=B, width=1):
        self.d.ellipse(box, fill=None if fill is None else self.ink(fill), outline=self.ink(outline), width=width)

    def poly(self, pts, fill=B, outline=None):
        self.d.polygon(pts, fill=None if fill is None else self.ink(fill),
                       outline=None if outline is None else self.ink(outline))

    def rect(self, box, fill=B):
        self.d.rectangle(box, fill=self.ink(fill))

    def line(self, pts, c=B, width=1):
        self.d.line(pts, fill=self.ink(c), width=width)

    def px(self, x, y, c=B):
        if 0 <= x < SIZE and 0 <= y < SIZE:
            self.img.putpixel((x, y), self.ink(c))

    def arc(self, box, start, end, c=B, width=1):
        self.d.arc(box, start, end, fill=self.ink(c), width=width)

    def pattern(self, mask_fn, box, kind):
        """Fills the pixels of box where mask_fn(x, y) with a pattern: 'check' (a gray), 'hatch', 'solid'."""
        x0, y0, x1, y1 = box
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                if not mask_fn(x, y):
                    continue
                if kind == 'solid' or (kind == 'check' and (x + y) % 2 == 0) or \
                        (kind == 'hatch' and (x - y) % 3 == 0):
                    self.px(x, y)
                else:
                    self.px(x, y, W)


# ---- The parts of a pirate ----

FACE = (18, 16, 46, 48)  # The head (x0, y0, x1, y1)


def body(p, kind='plain'):
    """The shoulders at the bottom: 'stripes' (a sailor shirt), 'coat' (lapels and buttons), 'plain'."""
    p.poly([(6, 63), (12, 52), (24, 48), (40, 48), (52, 52), (58, 63)], fill=W, outline=B)
    p.line([(6, 63), (12, 52), (24, 48)])
    p.line([(40, 48), (52, 52), (58, 63)])
    if kind == 'stripes':
        for y in (53, 57, 61):
            p.line([(10, y), (54, y)])
        p.poly([(6, 63), (12, 52), (24, 48), (40, 48), (52, 52), (58, 63)], fill=None, outline=B)
    elif kind == 'coat':
        p.poly([(24, 48), (32, 63), (12, 63), (13, 53)], fill=B)
        p.poly([(40, 48), (32, 63), (52, 63), (51, 53)], fill=B)
        for y in (54, 58, 62):
            p.px(26, y, W); p.px(38, y, W)
    p.line([(24, 48), (32, 56), (40, 48)])  # The collar


def head(p):
    p.ellipse(FACE, fill=W, outline=B, width=1)
    p.ellipse((15, 29, 19, 36), fill=W)  # Ears
    p.ellipse((45, 29, 49, 36), fill=W)
    p.ellipse(FACE, fill=W, outline=B)


def eyes(p, patch=False, angry=False):
    p.rect((25, 31, 27, 33)); p.rect((37, 31, 39, 33))
    if angry:
        p.line([(23, 28), (28, 30)], width=1); p.line([(36, 30), (41, 28)], width=1)
    else:
        p.line([(24, 28), (28, 28)]); p.line([(36, 28), (40, 28)])
    if patch:
        p.ellipse((34, 29, 42, 36), fill=B)
        p.line([(19, 22), (34, 31)]); p.line([(42, 31), (46, 27)])


def nose(p):
    p.line([(32, 33), (31, 38), (33, 38)])


def mouth(p, kind='smile'):
    if kind == 'smile':
        p.arc((26, 36, 38, 44), 20, 160)
    elif kind == 'worried':
        p.arc((27, 41, 37, 47), 200, 340)
    elif kind == 'grin':
        p.poly([(26, 40), (38, 40), (35, 44), (29, 44)], fill=B)
        p.line([(29, 41), (35, 41)], c=W)
    elif kind == 'flat':
        p.line([(28, 42), (36, 42)])


def freckles(p):
    for x, y in ((23, 36), (25, 37), (39, 36), (41, 37)):
        p.px(x, y)


def mustache(p, kind='plain'):
    if kind == 'plain':
        p.poly([(23, 43), (25, 40), (29, 39), (35, 39), (39, 40), (41, 43), (38, 42), (34, 41), (30, 41), (26, 42)],
               fill=B)
    elif kind == 'curl':  # Upturned, the ends curled
        p.poly([(24, 38), (32, 38), (40, 38), (36, 40), (32, 39), (28, 40)], fill=B)
        p.line([(24, 38), (21, 35), (22, 33)]); p.line([(40, 38), (43, 35), (42, 33)])


def goatee(p):
    p.poly([(30, 44), (34, 44), (32, 50)], fill=B)


def stubble(p):
    for y in range(41, 48):
        for x in range(22, 43):
            if (x * 7 + y * 3) % 5 == 0 and inside_face(x, y) and not (27 <= x <= 37 and 39 <= y <= 43):
                p.px(x, y)


def inside_face(x, y):
    cx, cy = (FACE[0] + FACE[2]) / 2, (FACE[1] + FACE[3]) / 2
    rx, ry = (FACE[2] - FACE[0]) / 2 - 1, (FACE[3] - FACE[1]) / 2 - 1
    return ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1


def beard(p, kind):
    """A big beard under the mouth: 'check' (gray: Barbe-Bleue) or 'solid' (Barbe-Noire, with braids)."""
    pts = [(18, 34), (20, 44), (24, 52), (32, 58), (40, 52), (44, 44), (46, 34), (42, 40), (32, 44), (22, 40)]
    if kind == 'solid':
        pts = [(18, 34), (19, 46), (23, 56), (32, 62), (41, 56), (45, 46), (46, 34), (42, 40), (32, 44), (22, 40)]
    mask = Image.new('1', (SIZE, SIZE), 0)
    ImageDraw.Draw(mask).polygon(pts, fill=1)
    p.pattern(lambda x, y: mask.getpixel((x, y)), (0, 0, SIZE - 1, SIZE - 1), kind)
    p.poly(pts, fill=None, outline=B)
    p.poly([(27, 40), (37, 40), (35, 43), (29, 43)], fill=W, outline=B)  # The mouth in the beard
    if kind == 'solid':  # Braids with white ribbons
        for x in (26, 38):
            p.line([(x, 56), (x, 62)], width=3)
            p.line([(x - 1, 59), (x + 1, 59)], c=W)


def bandana(p, dots=False):
    p.d.chord((17, 10, 47, 34), 180, 360, fill=0)
    p.rect((17, 21, 47, 23))
    if dots:
        for x, y in ((24, 15), (32, 13), (40, 15), (28, 19), (36, 19), (22, 21), (42, 21)):
            p.px(x, y, W)
    p.poly([(46, 20), (55, 16), (53, 22)], fill=B)  # The knot and its tails
    p.poly([(46, 22), (56, 27), (52, 29)], fill=B)


def hair(p):
    """Messy hair on the top of the head (no hat)."""
    p.d.chord((18, 14, 46, 32), 180, 360, fill=0)
    for x in range(21, 41, 4):  # The tufts, all above the head
        p.poly([(x, 18), (x + 2, 11), (x + 4, 18)], fill=B)


def paper_hat(p):
    p.poly([(14, 22), (32, 2), (50, 22)], fill=W, outline=B)
    p.rect((14, 20, 50, 23), fill=B)
    for y in (12, 16):  # The lines of the newspaper
        p.line([(32 - (y - 2) * 18 // 20 + 4, y), (32 + (y - 2) * 18 // 20 - 4, y)])


def wide_hat(p):
    p.d.chord((20, 4, 44, 30), 180, 360, fill=0)
    p.ellipse((6, 18, 58, 26), fill=B)
    p.line([(21, 16), (43, 16)], c=W)


def bicorne(p):
    p.d.chord((8, 4, 56, 40), 180, 360, fill=0)
    p.rect((8, 20, 56, 22), fill=B)
    p.ellipse((29, 9, 35, 15), fill=W)  # The cockade
    p.px(32, 12)


def plumed_hat(p):
    p.d.chord((18, 6, 46, 32), 180, 360, fill=0)
    p.ellipse((4, 16, 60, 26), fill=B)
    # The feather, a long plume curving back over the brim, its white rib
    plume = [(46, 16), (40, 8), (30, 3), (18, 3), (8, 8), (4, 14), (10, 11), (20, 8), (30, 9), (38, 13)]
    p.poly(plume, fill=B)
    p.line([(44, 15), (36, 9), (26, 6), (16, 6), (7, 11)], c=W)


def tricorn(p, skull=False):
    p.poly([(8, 22), (14, 8), (32, 4), (50, 8), (56, 22), (32, 16)], fill=B)
    p.line([(10, 21), (32, 15), (54, 21)], c=W)
    if skull:
        p.ellipse((28, 6, 36, 13), fill=W, outline=W)
        p.px(30, 9); p.px(33, 9)
        p.line([(26, 15), (38, 11)], c=W); p.line([(26, 11), (38, 15)], c=W)


def earring(p):
    p.ellipse((44, 37, 49, 42), fill=None)


def scar(p):
    p.line([(37, 35), (42, 41)])
    for i in range(3):
        p.px(38 + i * 2, 37 + i * 2 - 1); p.px(38 + i * 2 - 1, 37 + i * 2 + 1)


# ---- The props ----

def mop(p):
    p.line([(56, 8), (56, 50)], width=2)
    p.rect((52, 49, 60, 51))
    for x in range(49, 64, 2):  # The strands of the mop, hanging
        p.line([(56 + (x - 56) // 3, 51), (x, 62)])


def duck(p):
    p.ellipse((48, 52, 62, 62), fill=W)
    p.ellipse((52, 44, 60, 52), fill=W)
    p.poly([(60, 47), (64, 48), (60, 50)], fill=B)
    p.px(57, 47)


def cannonball(p):
    p.ellipse((46, 46, 60, 60), fill=B)
    p.arc((48, 48, 56, 56), 200, 260, c=W)
    p.line([(53, 46), (55, 41), (58, 40)])  # The fuse
    for x, y in ((59, 37), (61, 39), (57, 36)):
        p.px(x, y)


def cutlass(p):
    p.line([(7, 50), (4, 40), (4, 32), (7, 24)], width=2)  # The curved blade, raised
    p.line([(3, 51), (11, 51)], width=2)  # The guard
    p.line([(7, 52), (7, 60)], width=2)  # The grip


def musket(p):
    p.line([(54, 63), (62, 20)], width=3)
    p.line([(61, 24), (63, 14)], width=1)


def rapier(p):
    p.line([(59, 14), (59, 52)], width=1)  # The blade, raised
    p.line([(55, 53), (63, 53)], width=2)  # The guard
    p.arc((55, 53, 63, 61), 0, 180)
    p.line([(59, 55), (59, 63)], width=2)  # The grip


def hook(p):
    p.poly([(50, 63), (51, 52), (61, 52), (63, 63)], fill=B)  # The sleeve, on the shoulder
    p.rect((53, 50, 61, 52), fill=B)  # The cuff
    p.line([(59, 50), (59, 45)], width=2)  # The shaft, then the curve of the hook, its point down (below the ear)
    p.arc((53, 40, 60, 48), 180, 360, width=2)
    p.line([(53, 44), (53, 47)], width=2)


def stars(p, n):
    for i in range(n):
        x = 4 + i * 6
        p.line([(x, 1), (x, 5)]); p.line([(x - 2, 3), (x + 2, 3)])


# ---- The 10 portraits ----

def portrait(rank):
    p = Pic()
    if rank == 0:  # Moussaillon: the ship's boy, messy hair, freckles, his mop
        body(p, 'stripes'); head(p); hair(p); eyes(p); nose(p); mouth(p, 'smile'); freckles(p); mop(p)
    elif rank == 1:  # Pirate d'eau douce: a paper hat and a rubber duck
        body(p, 'stripes'); head(p); paper_hat(p); eyes(p); nose(p); mouth(p, 'worried'); duck(p)
    elif rank == 2:  # Matelot: the bandana of the sailor
        body(p, 'stripes'); head(p); bandana(p); eyes(p); nose(p); mouth(p, 'smile')
    elif rank == 3:  # Canonnier: the gunner and his cannonball
        body(p, 'plain'); head(p); bandana(p, dots=True); eyes(p, angry=True); nose(p); mouth(p, 'grin')
        p.px(23, 40); p.px(24, 41); p.px(41, 39)  # Soot
        cannonball(p)
    elif rank == 4:  # Flibustier: earring, mustache, cutlass
        body(p, 'plain'); head(p); bandana(p, dots=True); eyes(p); nose(p); mustache(p); earring(p); cutlass(p)
    elif rank == 5:  # Boucanier: the wide hat of the buccaneer, stubble, a scar, the musket
        body(p, 'plain'); head(p); wide_hat(p); eyes(p); nose(p); stubble(p); mouth(p, 'flat'); musket(p)
    elif rank == 6:  # Corsaire: the bicorne of the privateer, his coat
        body(p, 'coat'); head(p); bicorne(p); eyes(p); nose(p); mustache(p)
    elif rank == 7:  # Capitaine Fracasse: the plumed hat, the curled mustache, the rapier
        body(p, 'coat'); head(p); plumed_hat(p); eyes(p); nose(p); mustache(p, 'curl'); goatee(p); rapier(p)
    elif rank == 8:  # Barbe-Bleue: the tricorn, the patch, a big gray ("blue") beard
        body(p, 'coat'); head(p); tricorn(p); eyes(p, patch=True); nose(p); beard(p, 'check'); stars(p, 0)
    else:  # Barbe-Noire: the skull on the tricorn, the black braided beard, the hook
        body(p, 'coat'); head(p); tricorn(p, skull=True); eyes(p, patch=True, angry=True); nose(p)
        beard(p, 'solid'); hook(p)
    return p.img


def bits(img):
    """The rows of the portrait: 8 bytes each, 1 = black."""
    out = []
    for y in range(SIZE):
        row = []
        for bx in range(SIZE // 8):
            v = 0
            for i in range(8):
                if img.getpixel((bx * 8 + i, y)) == 0:
                    v |= 0x80 >> i
            row.append(v)
        out.append(row)
    return out


def c_block():
    lines = [BEGIN, '#define RANK_PORTRAIT_SIZE %d' % SIZE,
             'static const uint8_t RANK_PORTRAITS[%d][%d] = {' % (len(RANKS), SIZE * SIZE // 8)]
    for k, name in enumerate(RANKS):
        lines.append('    {  /* %s */' % name)
        for row in bits(portrait(k)):
            lines.append('        ' + ', '.join('0x%02X' % v for v in row) + ',')
        lines.append('    },')
    lines += ['};', END]
    return '\n'.join(lines)


def updated_source():
    with open(C_FILE, encoding='utf-8', newline='') as f:
        src = f.read()
    a, b = src.index(BEGIN), src.index(END) + len(END)
    nl = '\r\n' if '\r\n' in src else '\n'
    return src, src[:a] + c_block().replace('\n', nl) + src[b:]


def contact_sheet(path, zoom=2, cols=5):
    """The portraits at the size of the badge (zoom 2), the level and the name of the rank under each."""
    cell_w, cell_h, label = SIZE * zoom + 24, SIZE * zoom + 52, 40
    rows = (len(RANKS) + cols - 1) // cols
    sheet = Image.new('L', (cell_w * cols + 8, cell_h * rows + 8), 255)
    d = ImageDraw.Draw(sheet)
    font = ImageFont.load_default(size=14)
    for k, name in enumerate(RANKS):
        x, y = 8 + (k % cols) * cell_w + 8, 8 + (k // cols) * cell_h
        img = portrait(k).resize((SIZE * zoom, SIZE * zoom), Image.NEAREST).convert('L')
        sheet.paste(img, (x, y))
        d.rectangle((x - 1, y - 1, x + SIZE * zoom, y + SIZE * zoom), outline=0)
        d.text((x + SIZE * zoom // 2, y + SIZE * zoom + 6), '%d. %s' % (k + 1, name), fill=0, font=font, anchor='mt')
    sheet.save(path)
    print('wrote', path)


def main():
    parser = argparse.ArgumentParser(description='Portraits of the pirate ranks')
    parser.add_argument('--png', help='contact sheet of the portraits instead (PNG file)')
    parser.add_argument('--check', action='store_true', help='exit code 1 when src/menu/rank.c is not up to date')
    args = parser.parse_args()
    if args.png:
        contact_sheet(args.png)
        return
    src, new = updated_source()
    if args.check:
        print('up to date' if src == new else 'src/menu/rank.c is not up to date: python tools/pirate_ranks.py')
        sys.exit(0 if src == new else 1)
    if src != new:
        with open(C_FILE, 'w', encoding='utf-8', newline='') as f:
            f.write(new)
    print('wrote', C_FILE)


if __name__ == '__main__':
    main()
